### ISSUE TITLE
We need help with dependency settings

### ISSUE THREAD

**Issue by xaca** [xaca/juego_banderas#62]
Hello, please help us to update this project to remove warnings

Thank you!

**Comment by m4tr1k** [comment]
@xaca can I try solve this?

**Comment by xaca** [comment]
@m4tr1k Yes please 🙏 , also if you have some recomendations to avoid this problem again, please leave some tips 🤓 . Thank you!

**Comment by m4tr1k** [comment]
@xaca gonna take a look at the code and see what I can do!

**Comment by xaca** [comment]
@m4tr1k Thank you! great 👌

**Comment by m4tr1k** [comment]
@xaca can you please ellaborate what's happening? because when I run the project (with `grunt`), I get this:
![image](https://user-images.githubusercontent.com/12871065/94847837-05a10980-041b-11eb-9063-a4a1d1f2217e.png)

I'm not completely familiar with Grunt and I think the readme lacks some info about the installation part

**Comment by RanjithGovindaraj** [comment]
Hello,
I can't seem to find the issue
![issue image](https://user-images.githubusercontent.com/44660650/94917517-4dcd3400-04ce-11eb-9413-ed88609d25e4.png)
is this the warning we have to resolve?

**Comment by xaca** [comment]
@RanjithGovindaraj Yes please, remove warnings 🐛 ⚠️

**Comment by xaca** [comment]
@m4tr1k I have to review whats happening, because grunt lately has deprecated a lot of dependencies
